name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    paths:
      - 'worker/index.js'
      - 'worker/wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 5ccd9fe98b04e22bcbe058417639e367
          workingDirectory: worker
          secrets: |
            GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
